# Generated by Django 4.1.13 on 2024-03-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Just_type_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('letters', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Errors',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('letters', models.JSONField()),
            ],
        ),
    ]
