# Generated by Django 4.1.13 on 2024-03-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Just_type_api', '0003_userdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='user_data',
        ),
    ]
