# Generated by Django 4.1.13 on 2024-01-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Just_type_api', '0005_user_date_joined_user_first_name_user_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Errors_Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('lettersRu', models.JSONField()),
                ('lettersEn', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Words_Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('letters', models.JSONField()),
            ],
        ),
    ]
