# Generated by Django 4.1.13 on 2024-03-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Just_type_api', '0006_user_data_averagewpm_alter_user_data_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='averageWPM',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='bestWPM',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='experience',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='level',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='total_tests',
            field=models.IntegerField(default=None),
        ),
    ]
