# Generated by Django 4.1.13 on 2024-01-10 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Just_type_api', '0006_errors_letters_words_bank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words_Bank',
            new_name='All_Words',
        ),
        migrations.RenameModel(
            old_name='Errors_Letters',
            new_name='User_Errors',
        ),
    ]
