# Generated by Django 4.1.13 on 2024-03-19 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Just_type_api', '0007_alter_user_data_averagewpm_alter_user_data_bestwpm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Experience',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experience', models.IntegerField(default=None)),
                ('level', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
            },
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='level',
        ),
    ]
