# Generated by Django 4.1.13 on 2024-01-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Just_type_api', '0007_rename_words_bank_all_words_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_errors',
            old_name='lettersEn',
            new_name='letters',
        ),
        migrations.RemoveField(
            model_name='user_errors',
            name='lettersRu',
        ),
    ]
