# Generated by Django 4.1.13 on 2024-01-11 13:17

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Just_type_api', '0008_rename_lettersen_user_errors_letters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_words',
            name='letters',
            field=djongo.models.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='user_errors',
            name='letters',
            field=djongo.models.fields.JSONField(),
        ),
    ]
