# Generated by Django 4.1.13 on 2024-03-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Just_type_api', '0013_rename_userid_user_data_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_data',
            old_name='averageWPM',
            new_name='average_WPM',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='bestWPM',
            new_name='average_accuracy',
        ),
        migrations.RenameField(
            model_name='user_data',
            old_name='total_tests',
            new_name='best_WPM',
        ),
        migrations.AddField(
            model_name='user_data',
            name='best_accuracy',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user_data',
            name='tests_count',
            field=models.IntegerField(default=None),
        ),
    ]
