# Generated by Django 4.1.13 on 2024-03-27 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Just_type_api', '0016_rename_all_words_allwords_rename_user_data_userdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexperience',
            name='user_id',
            field=models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
